In [1]:
import numpy as np 
import pandas as pd

In [2]:
df = pd.read_csv("NFLX.csv")

In [3]:
df.head()

,Date,Open,High,Low,Close,Adj Close,Volume
0,2018-02-05,262.000000,267.899994,250.029999,254.259995,254.259995,11896100
1,2018-02-06,247.699997,266.700012,245.000000,265.720001,265.720001,12595800
2,2018-02-07,266.579987,272.450012,264.329987,264.559998,264.559998,8981500
3,2018-02-08,267.079987,267.619995,250.000000,250.100006,250.100006,9306700
4,2018-02-09,253.850006,255.800003,236.110001,249.470001,249.470001,16906900

In [4]:
df.describe()

,Open,High,Low,Close,Adj Close,Volume
count,1009.000000,1009.000000,1009.000000,1009.000000,1009.000000,1.009000e+03
mean,419.059673,425.320703,412.374044,419.000733,419.000733,7.570685e+06
std,108.537532,109.262960,107.555867,108.289999,108.289999,5.465535e+06
min,233.919998,250.649994,231.229996,233.880005,233.880005,1.144000e+06
25%,331.489990,336.299988,326.000000,331.619995,331.619995,4.091900e+06
50%,377.769989,383.010010,370.880005,378.670013,378.670013,5.934500e+06
75%,509.130005,515.630005,502.529999,509.079987,509.079987,9.322400e+06
max,692.349976,700.989990,686.090027,691.690002,691.690002,5.890430e+07

In [6]:
df = df.drop(["Open","High","Low","Close","Volume"],axis=1)
df

            Date   Adj Close
0     2018-02-05  254.259995
1     2018-02-06  265.720001
2     2018-02-07  264.559998
3     2018-02-08  250.100006
4     2018-02-09  249.470001
...          ...         ...
1004  2022-01-31  427.140015
1005  2022-02-01  457.130005
1006  2022-02-02  429.480011
1007  2022-02-03  405.600006
1008  2022-02-04  410.170013

[1009 rows x 2 columns]

In [7]:
df = df.groupby("Date")['Adj Close'].sum().reset_index()
# Group the DataFrame by. 'Date' column, calculate the sum of 'Adj .Close' values for each date,
# and reset the index to obtain a new DataFrame with 'Date' and 'Adj Close' columns.

In [8]:
df

            Date   Adj Close
0     2018-02-05  254.259995
1     2018-02-06  265.720001
2     2018-02-07  264.559998
3     2018-02-08  250.100006
4     2018-02-09  249.470001
...          ...         ...
1004  2022-01-31  427.140015
1005  2022-02-01  457.130005
1006  2022-02-02  429.480011
1007  2022-02-03  405.600006
1008  2022-02-04  410.170013

[1009 rows x 2 columns]

In [9]:
df.Date = pd.to_datetime(df.Date) # Convert the 'Date' column to datetime format df['Date' ] == df.Date
df.head()

        Date   Adj Close
0 2018-02-05  254.259995
1 2018-02-06  265.720001
2 2018-02-07  264.559998
3 2018-02-08  250.100006
4 2018-02-09  249.470001

In [10]:
df.set_index(["Date"],inplace=True)
df.head()

             Adj Close
Date
2018-02-05  254.259995
2018-02-06  265.720001
2018-02-07  264.559998
2018-02-08  250.100006
2018-02-09  249.470001

In [11]:
df.info()

<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 1009 entries, 2018-02-05 to 2022-02-04
Data columns (total 1 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Adj Close  1009 non-null   float64
dtypes: float64(1)
memory usage: 15.8 KB